config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :followings, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]

    resources :book_comments, only: [:create, :destroy]
  end
  get '/search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true,
             length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true,
                   length: { in: 2..20 }
  validates :introduction,  length:  { maximum: 50 }

  has_many :books, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
  attachment :profile_image

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  #フォローする側から自分がフォローしている人取得
  has_many :followings, through: :relationships, source: :followed
  #ユーザーがフォローしている人全員取得
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  #フォローされる側からフォローされている人取得
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #ユーザーをフォローしている人全員取得

  def followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    @book_comment.save

  end

  def destroy
    #BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy

  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
    @book_new = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.page(params[:page])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.page(params[:page])
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    following = current_user.relationships.build(followed_id: params[:user_id])
    following.save
    redirect_to request.referer
  end

  def destroy
    following = current_user.relationships.find_by(followed_id: params[:user_id])
    following.destroy
    redirect_to request.referer
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:profile] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render "books/comment", book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render "books/comment", book: @book) %>");
$("#book_comment_comment").val("");

app/views/books/_comment.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
   <tr>
      <td>
        <%= link_to user_path(book_comment.user.id) do %>
          <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br />
          <%= book_comment.user.name %>
         <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
      <td><%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), class: "btn btn-danger btn-sm", method: :delete, remote: true %>
      </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/books/_list.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>errors prohibited this obj from being saved:
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>User info</h2>
<table class="table">
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
  <tr>
     <th>name</th>
     <th><%= user.name %></th>
  </tr>
  <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to followings_user_path(user.id) do %>
          <%= user.followings.count %>
        <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to followers_user_path(user.id) do %>
          <%= user.followers.count %>
        <% end %>
    </th>
  </tr>
</table>
<div class="row">
 <% if current_user != user %>
   <% if user.followed_by?(current_user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
 <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <span class="fas fa-user-cog"></span>
    <% end %>
 <% end %>

</div>
<h2 class="mt-3">New book</h2>
<%= form_with model:book, url:'/books', local:true do |f| %>
  <div class="form-group">
    <label for ="book_title">Title</label><br />
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <label for ="book_opinion">Opinion</label><br />
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label><br />
           <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label><br />
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %><br />
          <%= link_to "Show", book_path %> |
          <%= link_to "Back", books_path %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
         <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
         </thead>
         <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td class="favorite-btn-<%= book.id %>">
                  <%= render 'favorites/favorite-btn', book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
         </tbody>
        </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book_new, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr id="book_<%= @book.id %>">
         <td><%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br />
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn-<%= @book.id %>">
            <%= render "favorites/favorite-btn", book: @book %>
          </td>
           <td class="comments-count">コメント数：<%= @book.book_comments.count %></td>
           <% if @user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success btn-sm"  %></td>
              <td><%= link_to "Destroy", book_path(@book), class: "btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に消しますか？" %></td>
           <% end %>
        </tr>
      </table>
      <div class="book_comments">
      <%= render "books/comment", book: @book %>
      </div>
      <%= form_with model:[@book, @book_comment] do |f| %>
        <%= f.text_area :comment, size:"90x5" %><br>
        <%= f.submit "送信" %>
      <% end %>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
        ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
         ♡<%= book.favorites.count %>
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
     <i class="fas fa-book"></i>
    <strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcom to
        <i class="fas fa-book">
        </i>
        <strong>Bookers
        </strong>!!
      </h1>

      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>

      <p>about various books!</p>

      <div class="btn-wrapper col-10 max-auto">
         <div class="row">
           <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
         </div>
         <div class="row">
         <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3" %>
       　</div>
      </div>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<div class="container">
 <div class="col-md-12">
   <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr><% @datas.each do |user| %>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
            <% end %>
      </tbody>
    </table>
   <% elsif @model == "book" %>
    <h2>Books search for '<%= @value %>'</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @datas.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
              <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      　<% end %>
      </tbody>
    </table>
    <% end %>
 </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
        <label for="inputName">Name</label><br />
        <%= f.text_field :name, autofocus: true, id:"inputName" %>
      　</div>
      　<div class="form-group">
        <label for="inputImage">Image</label><br />
        <%= f.attachment_field :profile_image %>
      　</div>
      　<div class="form-group">
        <label for="inputName">Introduction</label><br />
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
      　</div>
      　<div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      　</div>
      <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
 <h2>Follower Users</h2>
　<% if @users.count > 0 %>
　 <div class="row">
    <table class="table">
        <div class="row"><thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr><% @users.each do |user| %>
            <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count %></td>
            <td><% if current_user != user %>
                    <% if user.followed_by?(current_user) %>
                      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                    <% else %>
                      <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                    <% end %>
                <% end %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
              <% end %>
        </tbody>
    </table>
  </div>
   <% else %>
    <div>ユーザーはいません</div>
  <% end %>
</div>

app/views/users/followings.html.erb
<div class="container">
  <h2>Follow Users</h2>
  <% if @users.count > 0 %>
  <div class="row">
    <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr><% @users.each do |user| %>
            <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数：<%= user.followers.count %></td>
            <td><% if current_user != user %>
                    <% if user.followed_by?(current_user) %>
                      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                    <% else %>
                      <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                    <% end %>
                <% end %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          　   <% end %>
        </tbody>
    </table>
  </div>
  <% else %>
     <div>ユーザーはいません</div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
       <h2>Users</h2>
        <table class="table">
             <thead>
               <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
             </thead>
             <tbody>
               <tr><% @users.each do |user| %>
                 <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
                 <td><%= user.name %></td>
                 <td>フォロー数：<%= user.followings.count %></td>
                 <td>フォロワー数：<%= user.followers.count %></td>
                 <td><% if current_user != user %>
                        <% if user.followed_by?(current_user) %>
                          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                        <% else %>
                          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                        <% end %>
                      <% end %>
                 </td>
                 <td><%= link_to "Show", user_path(user.id) %></td>
               </tr>
                   <% end %>
              </tbody>
          </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
       <h2>Books</h2>
          <table class="table table-hover table-inverse">
             <thead>
              <tr>
               <th></th>
               <th>Title</th>
               <th>Opinion</th>
               <th colspan="3"></th>
              </tr>
             </thead>

             <tbody>
              <% @books.each do |book| %>
              <tr>
               <td><%= link_to user_path(@user.id) do %>
                   <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><% end %></td>
                 <td><%= link_to book.title, book_path(book.id) %></td>
                 <td><%= book.body %></td>
                 <td class="favorite-btn-<%= book.id %>">
                   <%= render "favorites/favorite-btn", book: book %></td>
                 <td>コメント数：<%= book.book_comments.count %></td>
              </tr>
              <% end %>
              </tbody>
           </table>
       </div>
  </div>
</div>