config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :followings, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]

    resources :book_comments, only: [:create, :destroy]
  end
  get '/search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true,
             length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true,
                   length: { in: 2..20 }
  validates :introduction,  length:  { maximum: 50 }

  has_many :books, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
  attachment :profile_image

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  #フォローする側から自分がフォローしている人取得
  has_many :followings, through: :relationships, source: :followed
  #ユーザーがフォローしている人全員取得
  has_many :reverse_of_relationships, class_name:"Relationship", foreign_key: "followed_id", dependent: :destroy
  #フォローされる側からフォローされている人取得
  has_many :followers, through: :reverse_of_relationships, source: :follower
  #ユーザーをフォローしている人全員取得

  def followed_by?(user)
    reverse_of_relationships.find_by(follower_id: user.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @user = @book.user
    @book_new = Book.new
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.page(params[:page])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.page(params[:page])
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:profile] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" date-toggler="collaspe" date-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expand="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collaspe navbar-collaspe" id="navbarNavDropdown" >
            <ul class="navbar-nav ml-auto" >
            <% if user_signed_in? %>
              <li calss="nav-item">
                <%= link_to user_path(current_user.id),  class: 'nav-link text-light' do %>
                 <span class="fas fa-home"> Home </span>
                <% end %>
              </li>
              <li calss="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                 <span class="fas fa-users">Users</span>
                <% end %>
              </li>
              <li calss="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                 <span class="fas fa-book-open">Books</span>
                <% end %>
              </li>
              <li calss="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                 <span class="fas fa-sign-out-alt">logout</span>
                <% end %>
              </li>
            <% else %>
              <li calss="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                 <span class="fas fa-home">Home</span>
                <% end %>
              </li>
              <li calss="nav-item">
                <%= link_to home_about_path, class: 'nav-link text-light' do %>
                 <span class="fas fa-link">About</span>
                <% end %>
              </li>
              <li calss="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                 <span class="fas fa-user-plus">sign up</span>
                <% end %>
              </li>
              <li calss="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                 <span class="fas fa-sign-in-alt">login</span>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
      </div>
    </nav>
    </header>

app/views/layouts/_search.html.erb
<div class="row">
 <div class="mx-auto" style="margin: 25px 0 ;">
  <div class="search-fom">
   <%= form_with url:search_path, method: :get, local: true do |f| %>
    <%= f.text_field 'search[value]' %>
    <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical" }) %>
    <%= f.submit :"検索" %>
   <% end %>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/438fa90fd1.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
     <main>
      <% flash.each do |message_type, message| %>
       <%= content_tag :div, message, class: message_type %>
      <% end %>

      <% if user_signed_in? %>
        <%= render 'layouts/search' %>
      <% end %>
      <%= yield %>
     </main>
    <footer>
      <div class="container mt-5 ">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>